name: Docker

on:
    workflow_dispatch:
    push:
        branches: main
    
jobs:
    docker:
        name: Build & Push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build & Push Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: luyancib/randomwanli:latest